
package facturacion;

import java.awt.HeadlessException;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DELL
 */
public class interfaz_buscarempleados extends javax.swing.JInternalFrame {

//    Connection con = null;
//    PreparedStatement pst = null;
//    ResultSet rs = null;
    
    /**
     * Creates new form interfaz_buscarempleados
     */
    
    
    
    private Object[][] datostabla; 
    //control_empleados ctr = new control_empleados("Id_empleado","CUI","Apellidos","Nombre","Direccion","Fecha_nacimiento","Telefono","Fecha_contrato","Genero","Estado_civil","Email","Cargo","Horario","Salario","Estado");
    control_existencias ctr = new control_existencias();
    public interfaz_buscarempleados() {
        initComponents();
        mostrar_tabla();
        
    }
    
     public void mostrar_tabla(){
        control_empleados emp = new control_empleados("Id_empleado","CUI","Apellidos","Nombre","Direccion","Fecha_nacimiento","Telefono","Fecha_contrato","Genero","Estado_civil","Email","Cargo","Horario","Salario","Estado");       
        String[] columnas = {"Id_empleado","CUI","Apellidos","Nombre","Direccion","Fecha_nacimiento","Telefono","Fecha_contrato","Genero","Estado_civil","Email","Cargo","Horario","Salario","Estado"};
        datostabla = emp.consulta_empleados();
        DefaultTableModel datos = new DefaultTableModel(datostabla,columnas);
        jTable1.setModel(datos);
    }
     
     
    public void limpiar()
    {
       jTable1.setName("");
      
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id_empleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        idjTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cuijTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apelljTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomjTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dirjTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fenajTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        teljTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fecojTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        genjTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        estcivjTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailjTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cargojTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        horjTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        saljTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        estjTextField4 = new javax.swing.JTextField();

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setTitle("Personal Registrado");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Acualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        id_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_empleadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese ID del empleado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Id_empleado");

        jLabel3.setText("CUI");

        jLabel4.setText("Apellidos");

        apelljTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelljTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel6.setText("Direccion");

        jLabel7.setText("Fecha_nacimiento");

        jLabel8.setText("Telefono");

        jLabel9.setText("Fecha_contrato");

        jLabel10.setText("Genero");

        jLabel11.setText("Estado_civil");

        jLabel12.setText("Email");

        jLabel13.setText("Cargo");

        jLabel14.setText("Horario");

        jLabel15.setText("Salario");

        jLabel16.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(725, 725, 725))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(horjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idjTextField1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel6))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dirjTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(genjTextField1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                            .addComponent(estcivjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cuijTextField2)
                                .addComponent(fenajTextField1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(83, 83, 83)
                        .addComponent(saljTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teljTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(apelljTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailjTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estjTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomjTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(fecojTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cargojTextField5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(cuijTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apelljTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(nomjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dirjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(fenajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecojTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(teljTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(genjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(estcivjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(emailjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cargojTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(horjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(saljTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(estjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_empleadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        int fila = jTable1.getSelectedRow();
//        String cod = "";
//        cod = jTable1.getValueAt(fila, 0).toString();
//        
        
        try{
        PreparedStatement pst = cn.prepareStatement("UPDATE rrhh SET CUI='"+cuijTextField2.getText()+"',Apellidos='"+apelljTextField3.getText()+"',Nombre='"+nomjTextField4.getText()+"',Direccion='"+dirjTextField5.getText()+"',Fecha_nacimiento='"+fenajTextField1.getText()+"',Telefono='"+teljTextField2.getText()+"',Fecha_contrato='"+fecojTextField3.getText()+"',Genero='"+genjTextField1.getText()+"',Estado_civil='"+estcivjTextField2.getText()+"',Email='"+emailjTextField4.getText()+"',Cargo='"+cargojTextField5.getText()+"',Horario='"+horjTextField1.getText()+"',Salario='"+saljTextField2.getText()+"',Estado='"+estjTextField4.getText()+"' WHERE Id_empleado='"+idjTextField1.getText()+"'");
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Informacion actualizada");
        mostrar_tabla();
        //limpiar();
        }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }     
         
         
         
         
//        int row = jTable1.getSelectedRow();
//        String cell = jTable1.getModel().getValueAt(row, 0).toString();
//        String sql = "delete from rrhhh where Id_empleado="+cell;
//        try{
//              Connection con = (Connection) DriverManager.getConnection("jdbc:mysql:localhost:3306/bd");
//              PreparedStatement ps = con.prepareStatement("delete Id_empleado,CUI,Apellidos,Nombre,Direccion,Fecha_nacimiento,Telefono,Fecha_contrato,Genero,Estado_civil,Email,Cargo,Horario,Salario,Estado from rrhh;");
//        
//        }catch(Exception e)
//        {
//            
//        
//        
//        }
        
        
        
        
//        String[] columnas = {"Id_empleado","CUI","Apellidos","Nombre","Direccion","Fecha_nacimiento","Telefono","Fecha_contrato","Genero","Estado_civil","Email","Cargo","Horario","Salario","Estado"};
//        datostabla = ctr.consulta_empleados(id_empleado.getText());
//        DefaultTableModel datosemp;
//        datosemp = new DefaultTableModel(datostabla,columnas);
//        int fila = jTable1.getSelectedRow();
//        if(fila>=0)
//        {
//            datosemp.removeRow(fila);
//            JOptionPane.showMessageDialog(null, "Empleado removido");
//     
//        }
//        else 
//        {
//            
//           JOptionPane.showMessageDialog(null, "Seleccionar fila");        
//        }
//        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String[] columnas = {"Id_empleado","CUI","Apellidos","Nombre","Direccion","Fecha_nacimiento","Telefono","Fecha_contrato","Genero","Estado_civil","Email","Cargo","Horario","Salario","Estado"};
        datostabla = ctr.consulta_empleados(id_empleado.getText());
        DefaultTableModel datosemp = new DefaultTableModel(datostabla,columnas);
        jTable1.setModel(datosemp);
        id_empleado.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if(fila >=0 )
        {
           idjTextField1.setText(jTable1.getValueAt(fila, 0).toString());
           cuijTextField2.setText(jTable1.getValueAt(fila, 1).toString());
           apelljTextField3.setText(jTable1.getValueAt(fila, 2).toString());
           nomjTextField4.setText(jTable1.getValueAt(fila, 3).toString());
           dirjTextField5.setText(jTable1.getValueAt(fila, 4).toString());
           fenajTextField1.setText(jTable1.getValueAt(fila, 5).toString());
           teljTextField2.setText(jTable1.getValueAt(fila, 6).toString());
           fecojTextField3.setText(jTable1.getValueAt(fila, 7).toString());
           genjTextField1.setText(jTable1.getValueAt(fila, 8).toString());        
           estcivjTextField2.setText(jTable1.getValueAt(fila, 9).toString());
           emailjTextField4.setText(jTable1.getValueAt(fila, 10).toString());
           cargojTextField5.setText(jTable1.getValueAt(fila, 11).toString());
           horjTextField1.setText(jTable1.getValueAt(fila, 12).toString());
           saljTextField2.setText(jTable1.getValueAt(fila, 13).toString());
           estjTextField4.setText(jTable1.getValueAt(fila, 14).toString());
        
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "No selecciono fila");
        
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void apelljTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelljTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelljTextField3ActionPerformed

    
    conexion cc=new conexion();
    Connection cn = cc.conectado();
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String cod = "";
        cod = jTable1.getValueAt(fila, 0).toString();
        
        
        try{
        PreparedStatement pst = cn.prepareStatement("DELETE FROM rrhh WHERE Id_empleado='"+cod+"'");
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Empleado removido");
        mostrar_tabla();
        //limpiar();
        }
        catch(SQLException e){
        
        }
        
        
        
            //ANTERIROMENTE ESTE METODO PERTENECIA AL BOTON ELIMINAR
        //        int fila = jTable1.getSelectedRow();
        //        String cod = "";
        //        cod = jTable1.getValueAt(fila, 0).toString();
        //
        //
        //        try{
            //        PreparedStatement pst = cn.prepareStatement("DELETE FROM rrhh WHERE Id_empleado='"+cod+"'");
            //        pst.executeUpdate();
            //        JOptionPane.showMessageDialog(null, "Empleado removido");
            //        mostrar_tabla();
            //        limpiar();
            //        }
        //        catch(SQLException e){
            //
            //        }

        //        try
        //
        //            String sql = "DELETE FROM rrhh WHERE Id_empleado =?";
        //            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd", "root", "");
        //            pst = con.prepareStatement(sql);
        //            pst.setString(1, Id_empleado);
        //            pst.executeUpdate();
        //            JOptionPane.showMessageDialog(null, "delete succesfully");
        //
        //        }
        //        catch(SQLException | HeadlessException ex){
            //             JOptionPane.showMessageDialog(null, ex);
            //
            //        }

        // TODO add your handling code here:
        //String[] columnas = {"Id_empleado","CUI","Apellidos","Nombre","Direccion","Fecha_nacimiento","Telefono","Fecha_contrato","Genero","Estado_civil","Email","Cargo","Horario","Salario","Estado"};
        //datostabla = ctr.consulta_empleados2(id_empleado.getText());
        //DefaultTableModel datosemp = new DefaultTableModel(datostabla,columnas);
        //       int row = jTable2.getSelectedRow();
        //       DefaultTableModel model= (DefaultTableModel)jTable2.getModel();
        //
        //       String selected = model.getValueAt(row, 0).toString();
        //
        //            if (row >= 0) {
            //
            //                model.removeRow(row);
            //
            //                try {
                //                    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/db", "root", "");
                //                    PreparedStatement ps = con.prepareStatement("DELETE from rrhh where Id_empleado='"+selected+"';");
                //                    ps.executeUpdate();
                //                }
            //                catch (SQLException w) {
                //                    JOptionPane.showMessageDialog(this, "Empleado removido");
                //                }
            //            }
    
        
          
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apelljTextField3;
    private javax.swing.JTextField cargojTextField5;
    private javax.swing.JTextField cuijTextField2;
    private javax.swing.JTextField dirjTextField5;
    private javax.swing.JTextField emailjTextField4;
    private javax.swing.JTextField estcivjTextField2;
    private javax.swing.JTextField estjTextField4;
    private javax.swing.JTextField fecojTextField3;
    private javax.swing.JTextField fenajTextField1;
    private javax.swing.JTextField genjTextField1;
    private javax.swing.JTextField horjTextField1;
    private javax.swing.JTextField id_empleado;
    private javax.swing.JTextField idjTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomjTextField4;
    private javax.swing.JTextField saljTextField2;
    private javax.swing.JTextField teljTextField2;
    // End of variables declaration//GEN-END:variables
}
